on: push

name: Test Find Issue Keys

jobs:
  test-find-issue-key:
    name: Find Issue Key
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@3

    - name: Login
      uses: govcms-extras/github-action-jira-connect@main
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Find Issue Key
      uses: ./
      with:
        from: commits

    - name: Find Issue Key
      id: find
      uses: ./
      with:
        string: Search is performed in this string. FIND-1 will be found

    - name: Find Issue Key
      uses: ./
      with:
        string: ${{ github.event.ref }} will search in branch name

    - name: should skip if working, or else error out
      if: ${{ steps.find.outputs.issue == '' }}
      run: echo "Issue not found" && exit 1

    - name: Find issue info
      run: echo "Issue ${{ steps.find.outputs.issue }} was found"
