# This is a basic workflow to help you get started with Actions

name: Node.js CI

on:
  push:
    branches: [ main  ]
 # pull_request:
   # branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Deploy NodeJS app
      uses: appleboy/ssh-action@v0.1.2
      with:
          host: ${{ secrets.SSH_HOST }} #public IP
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
	  script: |
	     cd /var/www/html/gem_frontend
	     touch text.txt
