name: JIRA and Confluence Workflow

on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install atlassian-python-api
          pip install jira

      - name: Run workflow
        run: |
          python my_workflow.py
